window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 1.0
  # opacity: 0.80

  # Window title
  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  gtk_theme_variant: light

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  #multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  #auto_scroll: false

# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
#tabspaces: 8

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono Nerd Font Mono

    style: Italic

  # Point size
  size: 12

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 1

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

schemes:
  AtomOneLight: &AtomOneLight
    primary:
      background: '0xf8f8f8'
      foreground: '0x2a2b33'

    normal:
      black:   '0x000000'
      red:     '0xde3d35'
      green:   '0x3e953a'
      yellow:  '0xd2b67b'
      blue:    '0x2f5af3'
      magenta: '0xa00095'
      cyan:    '0x3e953a'
      white:   '0xbbbbbb'

    bright:
      black:   '0x000000'
      red:     '0xde3d35'
      green:   '0x3e953a'
      yellow:  '0xd2b67b'
      blue:    '0x2f5af3'
      magenta: '0xa00095'
      cyan:    '0x3e953a'
      white:   '0xffffff'

colors: *AtomOneLight

# cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  # style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  #unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

key_bindings:
  - { key: Return, mods: Control, action: CreateNewWindow }
