return {
	settings = {
		intelephense = {
			files = {
				associations = { "*.php", "*.phtml", "*.module", "*.inc" }, -- e.g. Drupal
				exclude = { "**/node_modules/**", "**/.git/**" },
			},
			stubs = {
				"apache",
				"bcmath",
				"bz2",
				"Core",
				"ctype",
				"curl",
				"date",
				"dom",
				"fileinfo",
				"filter",
				"ftp",
				"gd",
				"gettext",
				"hash",
				"iconv",
				"json",
				"ldap",
				"libxml",
				"mbstring",
				"mcrypt",
				"openssl",
				"pcntl",
				"pcre",
				"PDO",
				"pdo_mysql",
				"Phar",
				"posix",
				"readline",
				"Reflection",
				"session",
				"SimpleXML",
				"soap",
				"sockets",
				"SPL",
				"standard",
				"superglobals",
				"sysvsem",
				"sysvshm",
				"tokenizer",
				"xml",
				"xmlreader",
				"xmlwriter",
				"zip",
				"zlib",
				"wordpress",
				"woocommerce",
				"acf-pro",
			},
			completion = {
				fullyQualifyGlobalConstantsAndFunctions = false,
				insertUseDeclaration = true,
			},
			diagnostics = {
				enable = true,
			},
		},
	},
}
